---
- name: install prerequisite packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - reboot-notifier

- name: apt upgrade
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 300

- name: 'Reboot if necessary'
  stat:
    path: /var/run/reboot-required
  register: result
  changed_when: result.stat.exists
  notify: 'restart server'
