---

- name: install piHole prerequisite packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - git
    - apt-utils
    - dialog
    - debconf
    - dhcpcd5
    - git 
    - iproute2
    - whiptail
    - bc 
    - cron
    - iputils-ping
    - lsof
    - psmisc
    - unzip
    - wget
    - idn2
    - sqlite3
    - libcap2-bin
    - dns-root-data
    - resolvconf
    - lighttpd
    - php7.0-common
    - php7.0-cgi
    - php7.0-sqlite3
