---

- name: remove debian apt repos
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb http://ftp.uk.debian.org/debian stretch main"
    - "deb-src http://ftp.uk.debian.org/debian stretch main"
    - "deb http://security.debian.org/debian-security stretch/updates main"
    - "deb-src http://security.debian.org/debian-security stretch/updates main"
    - "deb http://ftp.uk.debian.org/debian stretch-updates main"
    - "deb-src http://ftp.uk.debian.org/debian stretch-updates main"
  notify: clean apt cache

- name: re-add debian apt repos with contrib and non-free
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb http://deb.debian.org/debian stretch main contrib non-free"
    - "deb-src http://deb.debian.org/debian stretch main contrib non-free"
    - "deb http://deb.debian.org/debian stretch-updates main contrib non-free"
    - "deb-src http://deb.debian.org/debian stretch-updates main contrib non-free"
    - "deb http://security.debian.org/ stretch/updates main contrib non-free"
    - "deb-src http://security.debian.org/ stretch/updates main contrib non-free"
